"打开语法高亮
syntax on

"使用配色方案
colorscheme desert

"打开文件类型检测功能
filetype on

"不同文件类型采用不同缩进
filetype indent on

"允许使用插件
filetype plugin on
filetype plugin indent on

"关闭vi模式
set nocp

"显示行号, 或set number
set nu

"允许使用鼠标点击定位
set mouse=a

"允许区域选择
set selection=exclusive
set selectmode=mouse,key

"高亮光标所在行
set cursorline

"取消光标闪烁
set novisualbell

"总是显示状态行
set laststatus=2

"状态栏显示当前执行的命令
set showcmd

"标尺功能，显示当前光标所在行列号
set ruler

"设置命令行高度为3
"set cmdheight=3

"高亮显示匹配的括号
set showmatch

"继承前一行的缩进方式，特别适用于多行注释
set autoindent

"为C程序提供自动缩进
set smartindent

"制表符为4
set ts=4
set expandtab

"统一缩进为4
set softtabstop=4
set shiftwidth=4

"光标移动到buffer的顶部和底部时保持3行距离, 或set so=3
set scrolloff=3

"与windows共享剪贴板
set clipboard+=unnamed


